[theme]
base                     = "light"
primaryColor             = "#059669"
backgroundColor          = "#eef2f7"
secondaryBackgroundColor = "#ffffff"
textColor                = "#0f172a"
font                     = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
