[theme]
base                     = "light"
primaryColor             = "#059669"
backgroundColor          = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor                = "#18181b"
font                     = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
